// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFIXo6iQW-yFNHXlp0GSolzi4L_6qfty0',
    appId: '1:160894481689:web:807e77bc076103cc168188',
    messagingSenderId: '160894481689',
    projectId: 'restapicar',
    authDomain: 'restapicar.firebaseapp.com',
    databaseURL: 'https://restapicar-default-rtdb.firebaseio.com',
    storageBucket: 'restapicar.appspot.com',
    measurementId: 'G-6R5G08XFZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW7ymvDihV7DMALHC8-IK7TGendzf8720',
    appId: '1:160894481689:android:ff05203ee9799197168188',
    messagingSenderId: '160894481689',
    projectId: 'restapicar',
    databaseURL: 'https://restapicar-default-rtdb.firebaseio.com',
    storageBucket: 'restapicar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLTWpcG-TY6xyKa9ijcwYDTYTnsqwqE5w',
    appId: '1:160894481689:ios:cbde07c05cfeb0c3168188',
    messagingSenderId: '160894481689',
    projectId: 'restapicar',
    databaseURL: 'https://restapicar-default-rtdb.firebaseio.com',
    storageBucket: 'restapicar.appspot.com',
    iosBundleId: 'com.example.rentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLTWpcG-TY6xyKa9ijcwYDTYTnsqwqE5w',
    appId: '1:160894481689:ios:07092fce456c87a0168188',
    messagingSenderId: '160894481689',
    projectId: 'restapicar',
    databaseURL: 'https://restapicar-default-rtdb.firebaseio.com',
    storageBucket: 'restapicar.appspot.com',
    iosBundleId: 'com.example.rentalApp.RunnerTests',
  );
}
